package com.galacticai.flareconverter.models.ffmpeg.media_info.codec

@Deprecated("dynamic instead of this static thingie")
object CodecName {
    val image = listOf(
        "alias_pix", "apng", "bmp", "dpx", "exr", "fits", "gif", "hdr",
        "jpeg2000", "jpegls", "jpegxl", "ljpeg", "mjpg", "mjpeg", "pam",
        "pbm", "pcx", "pfm", "pgm", "pgmyuv", "phm", "png", "ppm", "qoi",
        "sgi", "sunrast", "targa", "tiff", "vbn", "wbmp", "webp", "xbm",
        "xface", "xpm", "xwd"
    )

    val video = listOf(
        "012v", "4xm", "8bps", "aasc", "agm", "aic", "alias_pix",
        "amv", "anm", "ansi", "apng", "arbc", "asv1", "asv2",
        "aura", "aura2", "av1", "avrn", "avrp", "avs", "avs2",
        "avs3", "bethsoftvid", "bfi", "binkvideo", "bintext",
        "bitpacked", "bmp", "bmv_video", "c93", "cavs", "cdgraphics",
        "cdtoons", "cdxl", "cfhd", "cinepak", "clearvideo",
        "cljr", "cllc", "cmv", "cpia", "cscd", "cyuv", "dds",
        "dfa", "dirac", "dnxhd", "dpx", "dsicinvideo", "dvvideo",
        "dxa", "dxtory", "dxv", "escape124", "escape130",
        "exr", "ffv1", "ffvhuff", "fic", "fits", "flashsv",
        "flashsv2", "flic", "flv1", "fmvc", "fraps", "frwu",
        "g2m", "gdv", "gif", "h261", "h263", "h263i", "h264",
        "hap", "hevc", "hnm4video", "hq_hqa", "hqx", "huffyuv",
        "hymt", "idcin", "idf", "iff_ilbm", "indeo2", "indeo3",
        "indeo4", "indeo5", "interplayvideo", "ipu", "jpeg2000",
        "jpegls", "jpegxl", "jv", "kgv1", "kmvc", "lagarith",
        "ljpeg", "loco", "m101", "mdec", "mimic", "mjpeg",
        "mjpeg_cuvid", "mjpegb", "mmvideo", "mobiclip",
        "motionpixels", "mpeg1video", "mpeg2video", "mpeg4",
        "mpegvideo", "msmpeg4v1", "msmpeg4v2", "msmpeg4v3",
        "msvideo1", "mszh", "mts2", "mv30", "mvc1", "mvc2",
        "mvdv", "mvha", "mxpeg", "nuv", "oggvideo", "paf_video",
        "pam", "pbm", "pcx", "pfm", "pgm", "pgmyuv", "pictor",
        "pixlet", "png", "ppm", "prores", "prosumer", "qdraw",
        "qoi", "qpeg", "qtrle", "r10k", "r210", "rasc", "rawvideo",
        "rl2", "roqvideo", "rpza", "rv10", "rv20", "rv30", "rv40",
        "sanm", "scpr", "screenpresso", "sgi", "sheervideo",
        "smc", "smvjpeg", "snow", "sp5x", "speedhq", "srgb",
        "sunrast", "svq1", "svq3", "targa", "theora", "thp",
        "tiertexseqvideo", "tiff", "tmv", "truemotion1",
        "truemotion2", "truemotion2rt", "tscc", "tscc2", "twinvq",
        "txd", "ulti", "utvideo", "v210", "v308", "v408", "v410",
        "vble", "vbn", "vnull", "vp3", "vp5", "vp6", "vp6a",
        "vp6f", "vp7", "vp8", "vp9", "vqc", "v for", "wbmp",
        "webp", "wmv1", "wmv2", "wmv3", "wrapped_avframe",
        "xan_wc3", "xan_wc4", "xbin", "xface", "xl", "xma1",
        "xma2", "xpm", "xwd", "y41p", "ylc", "yop", "yuv4",
        "zerocodec", "zlib", "zmbv"
    )

    val audio = listOf(
        "aac", "ac3", "acelp.kelvin", "adpcm_4xm", "adpcm_adx",
        "adpcm_argo", "adpcm_ct", "adpcm_dtk", "adpcm_ea",
        "adpcm_ea_maxis_xa", "adpcm_ea_r1", "adpcm_ea_r2",
        "adpcm_ea_r3", "adpcm_ea_xas", "adpcm_g722", "adpcm_g726",
        "adpcm_g726le", "adpcm_ima_acorn", "adpcm_ima_alp",
        "adpcm_ima_amv", "adpcm_ima_apc", "adpcm_ima_apm",
        "adpcm_ima_cunning", "adpcm_ima_dat4", "adpcm_ima_dk3",
        "adpcm_ima_dk4", "adpcm_ima_ea_eacs", "adpcm_ima_ea_sead",
        "adpcm_ima_iss", "adpcm_ima_moflex", "adpcm_ima_mtf",
        "adpcm_ima_oki", "adpcm_ima_qt", "adpcm_ima_rad",
        "adpcm_ima_smjpeg", "adpcm_ima_ssi", "adpcm_ima_wav",
        "adpcm_ima_ws", "adpcm_ms", "adpcm_mtaf", "adpcm_psx",
        "adpcm_sbpro_2", "adpcm_sbpro_3", "adpcm_sbpro_4",
        "adpcm_swf", "adpcm_thp", "adpcm_thp_le", "adpcm_vima",
        "adpcm_xa", "adpcm_xmd", "adpcm_yamaha", "alac", "amr_nb",
        "amr_wb", "ape", "aptx", "aptx_hd", "atrac1", "atrac3",
        "atrac3al", "atrac3p", "atrac3pal", "atrac9", "binkaudio_dct",
        "binkaudio_rdft", "bmv_audio", "bonk", "comfortnoise",
        "cook", "dca", "dfpwm", "dolby_e", "dts", "eac3", "evrc",
        "flac", "ftr", "g723_1", "g729", "gsm", "gsm_ms", "hcom",
        "iac", "ilbc", "imc", "interplay_dpcm", "interplayacm",
        "mace3", "mace6", "metasound", "mlp", "mp1", "mp2", "mp3",
        "mp3adu", "mp3on4", "mp4als", "musepack7", "musepack8",
        "nellymoser", "opus", "paf_audio", "pcm_alaw", "pcm_bluray",
        "pcm_dvd", "pcm_f16le", "pcm_f24le", "pcm_f32be", "pcm_f32le",
        "pcm_f64be", "pcm_f64le", "pcm_lxf", "pcm_mulaw",
        "pcm_s16be", "pcm_s16le", "pcm_s16le_planar", "pcm_s24be",
        "pcm_s24daud", "pcm_s24le", "pcm_s24le_planar", "pcm_s32be",
        "pcm_s32le", "pcm_s32le_planar", "pcm_s64be", "pcm_s64le",
        "pcm_s8", "pcm_s8_planar", "pcm_u16be", "pcm_u16le",
        "pcm_u24be", "pcm_u24le", "pcm_u32be", "pcm_u32le",
        "pcm_u8", "pcm_vidc", "qcelp", "qdm2", "qdmc", "ralf",
        "roq_dpcm", "s302m", "sbc", "shorten", "sierra_vmd",
        "smackaudio", "smv", "sol_dpcm", "sonic", "tak", "truehd",
        "truespeech", "tta", "twinvq", "vmdaudio", "vorbis", "wavpack",
        "wmalossless", "wmapro", "wmav1", "wmav2", "wmavoice", "ws_snd1",
        "xan_dpcm", "xma1", "xma2"
    )

    val subtitle = listOf(
        "subrip", "ass", "ssa", "webvtt", "mov_text",
        "text", "microdvd", "jacosub", "mpl2",
        "sami", "realtext", "subviewer", "subviewer1",
        "vplayer", "pjs", "stl", "dvb_subtitle",
        "dvb_teletext", "hdmv_pgs_subtitle", "xsub", "eia_608",
        "eia_708", "cc_dec", "arib_caption", "ttml", "bitmap",
    )
}